### ISSUE TITLE
[Bug] Recipe Editor not working

### ISSUE THREAD

**Issue by qwertyad1** [HuJohner/vscode-mc-datapack-ext#13]
When I right click, the option won't show up.

![image](https://user-images.githubusercontent.com/64162703/119163915-e0085500-ba29-11eb-8061-5821b3a4df10.png)

 The extension is enabled too.

![image](https://user-images.githubusercontent.com/64162703/119164051-04643180-ba2a-11eb-880b-6eb7d1d04477.png)

What do I do?

**Comment by HuJohner** [comment]
Make sure you are using the correct folder layout data/(namespace)/recipes

It looks like your file (test.json) is in the wrong place.

**Comment by qwertyad1** [comment]
It still won't pop up.
![image](https://user-images.githubusercontent.com/64162703/119706452-f9454300-be27-11eb-85f7-09631f890b60.png)
My namespace is op mobs
(opps, I closed it)

**Comment by HuJohner** [comment]
I believe 'recipes' has to be lowercase. So data/op_mobs/recipes/test.json

**Comment by qwertyad1** [comment]
how tf did i not close it TWO YEARS AGO
